alias: employees

target:
  primary-key: from_date
  table-name: employees
  engine-definition: ENGINE = MergeTree
      ORDER BY from_date
      SETTINGS index_granularity = 8192;

source:
  range-clause: where from_date > '{max_primary_key}'
  query: select e.emp_no, birth_date, s.from_date, s.to_date, s.salary
    from salaries s
    left join employees e on s.emp_no = e.emp_no

schedule:
  interval: PT30s
